const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST'
const FETCH_PRODUCT_SUCCEEDED = 'FETCH_PRODUCT_SUCCEEDED'
const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED'

export { FETCH_PRODUCT_SUCCEEDED, FETCH_PRODUCT_REQUEST, FETCH_PRODUCT_FAILED }