const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST'
const FETCH_LOGIN_SUCCEEDED = 'FETCH_LOGIN_SUCCEEDED'
const FETCH_LOGIN_FAILED = 'FETCH_LOGIN_FAILED'

export { FETCH_LOGIN_SUCCEEDED, FETCH_LOGIN_REQUEST, FETCH_LOGIN_FAILED }